### ISSUE TITLE
Won't run in Ubuntu 20.04 LTS default install of node/npm

### ISSUE THREAD

**Issue by hholst80** [gr2m/octoherd-script-rename-labels#2]
What more do I need here?

```
❯ npx octoherd-script-rename-labels
npx: installed 121 in 5.631s
Unexpected token {
❯ npx --version
6.14.4
❯ node --version
v10.19.0
❯ jq .version < package.json 
"0.0.0-development"
```

**Comment by gr2m** [comment]
Node 10 is no longer maintained. Can you upgrade to the latest stable version? See https://nodejs.org/en/

**Comment by hholst80** [comment]
I am still on Ubuntu 20.04 it seems. I'll try and upgrade to 22.04 once I get back to civilization. 

I did however find out that I could rename labels as part of the GitHub UI and my use case was just that.

Thank you for your feedback. I think we can close this as Ubuntu 22.04 has a newer Node as well.

**Comment by gr2m** [comment]
I think you should be able to upgrade the Node version independent of the Ubuntu version as well. Glad you got it worked out!
